const GAMES = [
  {
    "en": "StreetFighterII'-ChampionEdition(RedWavebootle",
    "zh": "街头霸王II-四大天王赤色波动",
    "category": "格斗游戏",
    "popularity": 99,
    "classic": 100,
    "recommendation": 99,
    "fun_score": 99.4,
    "rank": 1,
    "players": "双人对战",
    "complexity": "复杂",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c0",
    "year": "1992",
    "manufacturer": "Capcom"
  },
  {
    "en": "StreetFighterII'-ChampionEdition(TuLongbootleg",
    "zh": "街头霸王II-四大天王屠龙版",
    "category": "格斗游戏",
    "popularity": 100,
    "classic": 100,
    "recommendation": 98,
    "fun_score": 99.4,
    "rank": 2,
    "players": "双人对战",
    "complexity": "复杂",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c0",
    "year": "1992",
    "manufacturer": "Capcom"
  },
  {
    "en": "SuperStreetFighterIITurbo(superstreetfighter2",
    "zh": "超级街头霸王II加速版",
    "category": "格斗游戏",
    "popularity": 100,
    "classic": 99,
    "recommendation": 99,
    "fun_score": 99.4,
    "rank": 3,
    "players": "双人对战",
    "complexity": "复杂",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c0",
    "year": "1994",
    "manufacturer": "Capcom"
  },
  {
    "en": "KOF 97 ultimate battle",
    "zh": "拳皇97终极之战",
    "category": "格斗游戏",
    "popularity": 100,
    "classic": 98,
    "recommendation": 100,
    "fun_score": 99.3,
    "rank": 4,
    "players": "双人对战",
    "complexity": "复杂",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c0",
    "year": "1997",
    "manufacturer": "SNK"
  },
  {
    "en": "SuperStreetFighterII-thenewchallengers(supers",
    "zh": "超级街头霸王II-新的挑战者",
    "category": "格斗游戏",
    "popularity": 98,
    "classic": 99,
    "recommendation": 100,
    "fun_score": 98.9,
    "rank": 5,
    "players": "双人对战",
    "complexity": "复杂",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c0",
    "year": "1993",
    "manufacturer": "Capcom"
  },
  {
    "en": "KOF 98",
    "zh": "拳皇98",
    "category": "格斗游戏",
    "popularity": 100,
    "classic": 99,
    "recommendation": 97,
    "fun_score": 98.8,
    "rank": 6,
    "players": "双人对战",
    "complexity": "复杂",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c0",
    "year": "1998",
    "manufacturer": "SNK"
  },
  {
    "en": "StreetFighterII'-HyperFighting(streetfighter2'",
    "zh": "街头霸王II-战斗宣言",
    "category": "格斗游戏",
    "popularity": 100,
    "classic": 99,
    "recommendation": 96,
    "fun_score": 98.5,
    "rank": 7,
    "players": "双人对战",
    "complexity": "复杂",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c0",
    "year": "1992",
    "manufacturer": "Capcom"
  },
  {
    "en": "KOF 97 situation",
    "zh": "拳皇97风云",
    "category": "格斗游戏",
    "popularity": 98,
    "classic": 99,
    "recommendation": 98,
    "fun_score": 98.3,
    "rank": 8,
    "players": "双人对战",
    "complexity": "复杂",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c0",
    "year": "1997",
    "manufacturer": "SNK"
  },
  {
    "en": "KOF 97 strengthens",
    "zh": "拳皇97加强",
    "category": "格斗游戏",
    "popularity": 96,
    "classic": 98,
    "recommendation": 100,
    "fun_score": 97.9,
    "rank": 9,
    "players": "双人对战",
    "complexity": "复杂",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c0",
    "year": "1997",
    "manufacturer": "SNK"
  },
  {
    "en": "StreetFighterII-TheWorldWarrior(QuickenPt-Ibo",
    "zh": "街头霸王II-天下斗士加速",
    "category": "格斗游戏",
    "popularity": 97,
    "classic": 97,
    "recommendation": 100,
    "fun_score": 97.9,
    "rank": 10,
    "players": "双人对战",
    "complexity": "复杂",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c0",
    "year": "1991",
    "manufacturer": "Capcom"
  },
  {
    "en": "KOF 97",
    "zh": "拳皇97",
    "category": "格斗游戏",
    "popularity": 100,
    "classic": 97,
    "recommendation": 96,
    "fun_score": 97.7,
    "rank": 11,
    "players": "双人对战",
    "complexity": "复杂",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c0",
    "year": "1997",
    "manufacturer": "SNK"
  },
  {
    "en": "StreetFighterII-TheWorldWarrior(ThunderEdition",
    "zh": "街头霸王II-天下斗士雷霆版版",
    "category": "格斗游戏",
    "popularity": 95,
    "classic": 99,
    "recommendation": 99,
    "fun_score": 97.6,
    "rank": 12,
    "players": "双人对战",
    "complexity": "复杂",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c0",
    "year": "1991",
    "manufacturer": "Capcom"
  },
  {
    "en": "Super Street Fighter II - The New Challengers (Japan)",
    "zh": "超级街头霸王II: 新的挑战者",
    "category": "格斗游戏",
    "popularity": 97,
    "classic": 97,
    "recommendation": 99,
    "fun_score": 97.6,
    "rank": 13,
    "complexity": "复杂",
    "players": "双人对战",
    "saveable": "不支持存档",
    "data_src": "估算数据",
    "cc": "c0",
    "year": "",
    "manufacturer": ""
  },
  {
    "en": "StreetFighterII'-ChampionEdition(Accelerator!bo",
    "zh": "街头霸王II-四大天王加速",
    "category": "格斗游戏",
    "popularity": 94,
    "classic": 99,
    "recommendation": 100,
    "fun_score": 97.5,
    "rank": 14,
    "players": "双人对战",
    "complexity": "复杂",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c0",
    "year": "1992",
    "manufacturer": "Capcom"
  },
  {
    "en": "StreetFighterII'-ChampionEdition(Rainbowbootleg",
    "zh": "街头霸王II-四大天王彩虹版",
    "category": "格斗游戏",
    "popularity": 98,
    "classic": 98,
    "recommendation": 96,
    "fun_score": 97.4,
    "rank": 15,
    "players": "双人对战",
    "complexity": "复杂",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c0",
    "year": "1992",
    "manufacturer": "Capcom"
  },
  {
    "en": "StreetFighterII-TheWorldWarrior(910522etc)",
    "zh": "街头霸王II-天下斗士",
    "category": "格斗游戏",
    "popularity": 96,
    "classic": 100,
    "recommendation": 95,
    "fun_score": 97.1,
    "rank": 16,
    "players": "双人对战",
    "complexity": "复杂",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c0",
    "year": "1991",
    "manufacturer": "Capcom"
  },
  {
    "en": "StreetFighterII'-XiangLong(bootlegset1-811102",
    "zh": "街头霸王II-降龙",
    "category": "格斗游戏",
    "popularity": 94,
    "classic": 98,
    "recommendation": 99,
    "fun_score": 96.9,
    "rank": 17,
    "players": "双人对战",
    "complexity": "复杂",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c0",
    "year": "1991",
    "manufacturer": "Capcom"
  },
  {
    "en": "StreetFighterII'-MagicDeltaTurbo(bootlegset1",
    "zh": "街头霸王II-魔术三角洲加速版",
    "category": "格斗游戏",
    "popularity": 94,
    "classic": 97,
    "recommendation": 100,
    "fun_score": 96.8,
    "rank": 18,
    "players": "双人对战",
    "complexity": "复杂",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c0",
    "year": "1991",
    "manufacturer": "Capcom"
  },
  {
    "en": "KOF 2002 Plus",
    "zh": "拳皇2002风云Plus",
    "category": "格斗游戏",
    "popularity": 93,
    "classic": 99,
    "recommendation": 98,
    "fun_score": 96.6,
    "rank": 19,
    "players": "双人对战",
    "complexity": "复杂",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c0",
    "year": "2002",
    "manufacturer": "Eolith / Playmore"
  },
  {
    "en": "KOF 2002 Super",
    "zh": "拳皇2002 Supper",
    "category": "格斗游戏",
    "popularity": 96,
    "classic": 98,
    "recommendation": 94,
    "fun_score": 96.1,
    "rank": 20,
    "players": "双人对战",
    "complexity": "复杂",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c0",
    "year": "2002",
    "manufacturer": "Eolith / Playmore"
  },
  {
    "en": "TheKingofFighters2002Plus(bootlegset1)",
    "zh": "拳皇2002加强版",
    "category": "格斗游戏",
    "popularity": 94,
    "classic": 95,
    "recommendation": 99,
    "fun_score": 95.9,
    "rank": 21,
    "players": "双人对战",
    "complexity": "复杂",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c0",
    "year": "2002",
    "manufacturer": "Eolith / Playmore"
  },
  {
    "en": "TheKingofFighters2002(NGM-2650)",
    "zh": "拳皇2002",
    "category": "格斗游戏",
    "popularity": 95,
    "classic": 95,
    "recommendation": 98,
    "fun_score": 95.9,
    "rank": 22,
    "players": "双人对战",
    "complexity": "复杂",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c0",
    "year": "2002",
    "manufacturer": "Eolith / Playmore"
  },
  {
    "en": "Cadillacs&Dinosaurs(930201etc)",
    "zh": "恐龙新世纪",
    "category": "格斗游戏",
    "popularity": 95,
    "classic": 96,
    "recommendation": 96,
    "fun_score": 95.6,
    "rank": 23,
    "players": "多人",
    "complexity": "中等",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c0",
    "year": "1993",
    "manufacturer": "Capcom"
  },
  {
    "en": "KOF 2002 Magic",
    "zh": "拳皇2002魔幻",
    "category": "格斗游戏",
    "popularity": 92,
    "classic": 99,
    "recommendation": 95,
    "fun_score": 95.3,
    "rank": 24,
    "players": "双人对战",
    "complexity": "复杂",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c0",
    "year": "2002",
    "manufacturer": "Eolith / Playmore"
  },
  {
    "en": "KOF 2002 Magic 2",
    "zh": "拳皇2002魔幻2",
    "category": "格斗游戏",
    "popularity": 92,
    "classic": 99,
    "recommendation": 94,
    "fun_score": 95.0,
    "rank": 25,
    "players": "双人对战",
    "complexity": "复杂",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c0",
    "year": "2002",
    "manufacturer": "Eolith / Playmore"
  },
  {
    "en": "dino",
    "zh": "恐龙新世纪2011无双2018版",
    "category": "格斗游戏",
    "popularity": 94,
    "classic": 97,
    "recommendation": 94,
    "fun_score": 95.0,
    "rank": 26,
    "players": "多人",
    "complexity": "中等",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c0",
    "year": "1993",
    "manufacturer": "Capcom"
  },
  {
    "en": "KOF 2002 situation",
    "zh": "拳皇2002风云",
    "category": "格斗游戏",
    "popularity": 92,
    "classic": 95,
    "recommendation": 95,
    "fun_score": 93.9,
    "rank": 27,
    "players": "双人对战",
    "complexity": "复杂",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c0",
    "year": "2002",
    "manufacturer": "Eolith / Playmore"
  },
  {
    "en": "Probotector II - Return of the Evil Forces (Europe)",
    "zh": "超级魂斗罗2",
    "category": "射击游戏",
    "popularity": 88,
    "classic": 96,
    "recommendation": 95,
    "fun_score": 92.9,
    "rank": 28,
    "players": "双人合作",
    "complexity": "中等",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c1",
    "year": "",
    "manufacturer": ""
  },
  {
    "en": "spsudoluienvrfc",
    "zh": "超级魂斗罗20合1",
    "category": "射击游戏",
    "popularity": 92,
    "classic": 94,
    "recommendation": 91,
    "fun_score": 92.4,
    "rank": 29,
    "players": "双人合作",
    "complexity": "中等",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c1",
    "year": "",
    "manufacturer": ""
  },
  {
    "en": "ContraForce",
    "zh": "魂斗罗原版",
    "category": "射击游戏",
    "popularity": 90,
    "classic": 93,
    "recommendation": 94,
    "fun_score": 92.2,
    "rank": 30,
    "players": "双人合作",
    "complexity": "中等",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c1",
    "year": "",
    "manufacturer": ""
  },
  {
    "en": "hchevrfcb",
    "zh": "魂斗罗力量 hack（汉化版）",
    "category": "射击游戏",
    "popularity": 92,
    "classic": 95,
    "recommendation": 89,
    "fun_score": 92.1,
    "rank": 31,
    "players": "双人合作",
    "complexity": "中等",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c1",
    "year": "",
    "manufacturer": ""
  },
  {
    "en": "Air Contra",
    "zh": "空中魂斗罗",
    "category": "动作冒险",
    "popularity": 90,
    "classic": 94,
    "recommendation": 91,
    "fun_score": 91.7,
    "rank": 32,
    "players": "双人合作",
    "complexity": "中等",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c2",
    "year": "1987",
    "manufacturer": "Konami"
  },
  {
    "en": "Contra - Power",
    "zh": "魂斗罗",
    "category": "动作冒险",
    "popularity": 90,
    "classic": 93,
    "recommendation": 92,
    "fun_score": 91.6,
    "rank": 33,
    "players": "双人合作",
    "complexity": "中等",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c2",
    "year": "1987",
    "manufacturer": "Konami"
  },
  {
    "en": "bunhvrfc",
    "zh": "魂斗罗之真水下八关",
    "category": "射击游戏",
    "popularity": 88,
    "classic": 95,
    "recommendation": 92,
    "fun_score": 91.6,
    "rank": 34,
    "players": "双人合作",
    "complexity": "中等",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c1",
    "year": "",
    "manufacturer": ""
  },
  {
    "en": "Contra Force (USA)",
    "zh": "魂斗罗6",
    "category": "动作冒险",
    "popularity": 89,
    "classic": 94,
    "recommendation": 92,
    "fun_score": 91.6,
    "rank": 35,
    "players": "双人合作",
    "complexity": "中等",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c2",
    "year": "1987",
    "manufacturer": "Konami"
  },
  {
    "en": "SuperContra",
    "zh": "超级魂斗罗",
    "category": "动作冒险",
    "popularity": 86,
    "classic": 95,
    "recommendation": 94,
    "fun_score": 91.5,
    "rank": 36,
    "players": "双人合作",
    "complexity": "中等",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c2",
    "year": "1987",
    "manufacturer": "Konami"
  },
  {
    "en": "Yokoyama Mitsuteru Sangokushi (Japan)",
    "zh": "横山光辉三国志（日）",
    "category": "动作冒险",
    "popularity": 91,
    "classic": 93,
    "recommendation": 89,
    "fun_score": 91.1,
    "rank": 37,
    "complexity": "复杂",
    "players": "多人",
    "saveable": "不支持存档",
    "data_src": "估算数据",
    "cc": "c2",
    "year": "",
    "manufacturer": ""
  },
  {
    "en": "SangokushiII:SanJianSheng(Chinesebootlegset1-",
    "zh": "三国志三剑圣",
    "category": "动作冒险",
    "popularity": 90,
    "classic": 93,
    "recommendation": 90,
    "fun_score": 91.0,
    "rank": 38,
    "complexity": "复杂",
    "players": "多人",
    "saveable": "不支持存档",
    "data_src": "估算数据",
    "cc": "c2",
    "year": "",
    "manufacturer": ""
  },
  {
    "en": "OrientalLegend(V105-Korea)",
    "zh": "西游释厄传V105",
    "category": "格斗游戏",
    "popularity": 87,
    "classic": 93,
    "recommendation": 93,
    "fun_score": 90.9,
    "rank": 39,
    "players": "多人",
    "complexity": "复杂",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c0",
    "year": "1997",
    "manufacturer": "IGS"
  },
  {
    "en": "Contra -30 life S gun",
    "zh": "魂斗罗30条命",
    "category": "动作冒险",
    "popularity": 88,
    "classic": 93,
    "recommendation": 92,
    "fun_score": 90.9,
    "rank": 40,
    "players": "双人合作",
    "complexity": "中等",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c2",
    "year": "1987",
    "manufacturer": "Konami"
  },
  {
    "en": "OrientalLegend-XiYoGiShiReZuang(V111-China)",
    "zh": "西游释厄传V111",
    "category": "格斗游戏",
    "popularity": 91,
    "classic": 92,
    "recommendation": 89,
    "fun_score": 90.8,
    "rank": 41,
    "players": "多人",
    "complexity": "复杂",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c0",
    "year": "1997",
    "manufacturer": "IGS"
  },
  {
    "en": "Contra Iron Corps",
    "zh": "魂斗罗铁血兵团",
    "category": "动作冒险",
    "popularity": 87,
    "classic": 95,
    "recommendation": 90,
    "fun_score": 90.7,
    "rank": 42,
    "players": "双人合作",
    "complexity": "中等",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c2",
    "year": "1987",
    "manufacturer": "Konami"
  },
  {
    "en": "Final Fight 2 (USA)",
    "zh": "快打旋风2（美）",
    "category": "格斗游戏",
    "popularity": 90,
    "classic": 92,
    "recommendation": 90,
    "fun_score": 90.7,
    "rank": 43,
    "players": "双人对战",
    "complexity": "中等",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c0",
    "year": "1989",
    "manufacturer": "Capcom"
  },
  {
    "en": "Contra III - The Alien Wars (USA)",
    "zh": "魂斗罗3：异形战争（美）",
    "category": "动作冒险",
    "popularity": 87,
    "classic": 93,
    "recommendation": 92,
    "fun_score": 90.6,
    "rank": 44,
    "players": "双人合作",
    "complexity": "中等",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c2",
    "year": "1987",
    "manufacturer": "Konami"
  },
  {
    "en": "Sangokushi IV (Japan)",
    "zh": "三国志4（日）",
    "category": "动作冒险",
    "popularity": 91,
    "classic": 89,
    "recommendation": 92,
    "fun_score": 90.6,
    "rank": 45,
    "complexity": "复杂",
    "players": "多人",
    "saveable": "不支持存档",
    "data_src": "估算数据",
    "cc": "c2",
    "year": "",
    "manufacturer": ""
  },
  {
    "en": "WarriorsofFate(bootleg-921002etc)",
    "zh": "三国志2(A版-921002世界版)",
    "category": "格斗游戏",
    "popularity": 90,
    "classic": 92,
    "recommendation": 89,
    "fun_score": 90.4,
    "rank": 46,
    "players": "多人",
    "complexity": "中等",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c0",
    "year": "1992",
    "manufacturer": "Capcom"
  },
  {
    "en": "Interstellar Contra",
    "zh": "星际魂斗罗",
    "category": "动作冒险",
    "popularity": 88,
    "classic": 93,
    "recommendation": 90,
    "fun_score": 90.3,
    "rank": 47,
    "players": "双人合作",
    "complexity": "中等",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c2",
    "year": "1987",
    "manufacturer": "Konami"
  },
  {
    "en": "OrientalLegendSpecial-XiYoGiShiReZuangSuper",
    "zh": "西游释厄传超级版",
    "category": "格斗游戏",
    "popularity": 87,
    "classic": 90,
    "recommendation": 94,
    "fun_score": 90.1,
    "rank": 48,
    "players": "多人",
    "complexity": "中等",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c0",
    "year": "",
    "manufacturer": ""
  },
  {
    "en": "Romance of the Three Kingdoms III - Dragon of Destiny (USA)",
    "zh": "三国志3-龙之命运",
    "category": "动作冒险",
    "popularity": 91,
    "classic": 92,
    "recommendation": 87,
    "fun_score": 90.1,
    "rank": 49,
    "complexity": "复杂",
    "players": "多人",
    "saveable": "不支持存档",
    "data_src": "估算数据",
    "cc": "c2",
    "year": "",
    "manufacturer": ""
  },
  {
    "en": "Super Probotector - Alien Rebels (Europe)",
    "zh": "超级魂斗罗（欧）",
    "category": "射击游戏",
    "popularity": 86,
    "classic": 95,
    "recommendation": 89,
    "fun_score": 90.0,
    "rank": 50,
    "players": "双人合作",
    "complexity": "中等",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c1",
    "year": "",
    "manufacturer": ""
  },
  {
    "en": "OrientalLegend-XiYoGiShiReZuang(V126)",
    "zh": "西游释厄传",
    "category": "格斗游戏",
    "popularity": 85,
    "classic": 91,
    "recommendation": 94,
    "fun_score": 89.8,
    "rank": 51,
    "players": "多人",
    "complexity": "复杂",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c0",
    "year": "1997",
    "manufacturer": "IGS"
  },
  {
    "en": "SangokushiII(921005Asia)",
    "zh": "三国志2(亚洲版)",
    "category": "动作冒险",
    "popularity": 88,
    "classic": 93,
    "recommendation": 88,
    "fun_score": 89.8,
    "rank": 52,
    "complexity": "复杂",
    "players": "多人",
    "saveable": "不支持存档",
    "data_src": "估算数据",
    "cc": "c2",
    "year": "",
    "manufacturer": ""
  },
  {
    "en": "Contra (USA)",
    "zh": "魂斗罗（美）",
    "category": "动作冒险",
    "popularity": 88,
    "classic": 92,
    "recommendation": 89,
    "fun_score": 89.7,
    "rank": 53,
    "players": "双人合作",
    "complexity": "中等",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c2",
    "year": "1987",
    "manufacturer": "Konami"
  },
  {
    "en": "Romance of the Three Kingdoms IV - Wall of Fire (USA)",
    "zh": "三国志4",
    "category": "动作冒险",
    "popularity": 88,
    "classic": 90,
    "recommendation": 91,
    "fun_score": 89.6,
    "rank": 54,
    "complexity": "复杂",
    "players": "多人",
    "saveable": "支持存档",
    "data_src": "估算数据",
    "cc": "c2",
    "year": "",
    "manufacturer": ""
  },
  {
    "en": "Sangokushi Seishi - Tenbu Spirits (Japan)",
    "zh": "天舞三国志",
    "category": "动作冒险",
    "popularity": 85,
    "classic": 93,
    "recommendation": 91,
    "fun_score": 89.6,
    "rank": 55,
    "complexity": "复杂",
    "players": "多人",
    "saveable": "不支持存档",
    "data_src": "估算数据",
    "cc": "c2",
    "year": "",
    "manufacturer": ""
  },
  {
    "en": "Yokoyama Mitsuteru Sangokushi 2 (Japan)",
    "zh": "横山光辉三国志2",
    "category": "动作冒险",
    "popularity": 86,
    "classic": 92,
    "recommendation": 91,
    "fun_score": 89.6,
    "rank": 56,
    "complexity": "复杂",
    "players": "多人",
    "saveable": "不支持存档",
    "data_src": "估算数据",
    "cc": "c2",
    "year": "",
    "manufacturer": ""
  },
  {
    "en": "Yokoyama Mitsuteru Sangokushi Bangi - Sugoroku Eiyuu-ki (Japan)",
    "zh": "横山光辉三国志大富翁",
    "category": "动作冒险",
    "popularity": 85,
    "classic": 92,
    "recommendation": 92,
    "fun_score": 89.5,
    "rank": 57,
    "complexity": "复杂",
    "players": "多人",
    "saveable": "不支持存档",
    "data_src": "估算数据",
    "cc": "c2",
    "year": "",
    "manufacturer": ""
  },
  {
    "en": "FinalFight(Japan)",
    "zh": "快打旋风",
    "category": "格斗游戏",
    "popularity": 89,
    "classic": 92,
    "recommendation": 87,
    "fun_score": 89.4,
    "rank": 58,
    "players": "双人对战",
    "complexity": "中等",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c0",
    "year": "1989",
    "manufacturer": "Capcom"
  },
  {
    "en": "OrientalLegend-XiYoGiShiReZuang(V112-China)",
    "zh": "西游释厄传V112",
    "category": "格斗游戏",
    "popularity": 87,
    "classic": 92,
    "recommendation": 89,
    "fun_score": 89.3,
    "rank": 59,
    "players": "多人",
    "complexity": "复杂",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c0",
    "year": "1997",
    "manufacturer": "IGS"
  },
  {
    "en": "SangokushiII:HuoFenghuang(Chinesebootleg-921005",
    "zh": "三国志火凤凰",
    "category": "动作冒险",
    "popularity": 86,
    "classic": 93,
    "recommendation": 89,
    "fun_score": 89.3,
    "rank": 60,
    "complexity": "复杂",
    "players": "多人",
    "saveable": "不支持存档",
    "data_src": "估算数据",
    "cc": "c2",
    "year": "",
    "manufacturer": ""
  },
  {
    "en": "SangokushiII:SanguoYingxiongZhuan(Chinesebootleg",
    "zh": "三国志2",
    "category": "动作冒险",
    "popularity": 86,
    "classic": 90,
    "recommendation": 92,
    "fun_score": 89.2,
    "rank": 61,
    "complexity": "复杂",
    "players": "多人",
    "saveable": "不支持存档",
    "data_src": "估算数据",
    "cc": "c2",
    "year": "",
    "manufacturer": ""
  },
  {
    "en": "Super Sangokushi II (Japan)",
    "zh": "超级三国志2（日）",
    "category": "动作冒险",
    "popularity": 90,
    "classic": 91,
    "recommendation": 86,
    "fun_score": 89.1,
    "rank": 62,
    "complexity": "复杂",
    "players": "多人",
    "saveable": "不支持存档",
    "data_src": "估算数据",
    "cc": "c2",
    "year": "",
    "manufacturer": ""
  },
  {
    "en": "Sangokushi - Chuugen no Hasha (Japan)",
    "zh": "三国志-中原之霸者?",
    "category": "动作冒险",
    "popularity": 87,
    "classic": 91,
    "recommendation": 89,
    "fun_score": 89.0,
    "rank": 63,
    "complexity": "复杂",
    "players": "多人",
    "saveable": "不支持存档",
    "data_src": "估算数据",
    "cc": "c2",
    "year": "",
    "manufacturer": ""
  },
  {
    "en": "Final Fight 3 (USA)",
    "zh": "快打旋风3（美）",
    "category": "格斗游戏",
    "popularity": 87,
    "classic": 91,
    "recommendation": 89,
    "fun_score": 89.0,
    "rank": 64,
    "players": "双人对战",
    "complexity": "中等",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c0",
    "year": "1989",
    "manufacturer": "Capcom"
  },
  {
    "en": "OrientalLegend2(Korea)/XiYouShiEZhuanSuperP",
    "zh": "西游释厄传-群魔乱舞",
    "category": "格斗游戏",
    "popularity": 86,
    "classic": 90,
    "recommendation": 91,
    "fun_score": 88.9,
    "rank": 65,
    "players": "多人",
    "complexity": "中等",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c0",
    "year": "",
    "manufacturer": ""
  },
  {
    "en": "Garou-MarkoftheWolves(NGM-2530)",
    "zh": "饿狼传说-狼之烙印",
    "category": "格斗游戏",
    "popularity": 84,
    "classic": 92,
    "recommendation": 91,
    "fun_score": 88.9,
    "rank": 66,
    "complexity": "复杂",
    "players": "双人对战",
    "saveable": "不支持存档",
    "data_src": "估算数据",
    "cc": "c0",
    "year": "",
    "manufacturer": ""
  },
  {
    "en": "FatalFury-KingofFighters/GarouDensetsu-shuku",
    "zh": "饿狼传说-宿命之战",
    "category": "格斗游戏",
    "popularity": 86,
    "classic": 90,
    "recommendation": 91,
    "fun_score": 88.9,
    "rank": 67,
    "complexity": "复杂",
    "players": "双人对战",
    "saveable": "不支持存档",
    "data_src": "估算数据",
    "cc": "c0",
    "year": "",
    "manufacturer": ""
  },
  {
    "en": "Mighty Final Fight (USA)",
    "zh": "快打旋风（美）",
    "category": "格斗游戏",
    "popularity": 85,
    "classic": 90,
    "recommendation": 92,
    "fun_score": 88.8,
    "rank": 68,
    "players": "双人对战",
    "complexity": "中等",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c0",
    "year": "1989",
    "manufacturer": "Capcom"
  },
  {
    "en": "Sangokushi II - Haou no Tairiku (Japan)",
    "zh": "三国志霸王的大陆",
    "category": "动作冒险",
    "popularity": 88,
    "classic": 92,
    "recommendation": 86,
    "fun_score": 88.8,
    "rank": 69,
    "complexity": "复杂",
    "players": "多人",
    "saveable": "不支持存档",
    "data_src": "估算数据",
    "cc": "c2",
    "year": "",
    "manufacturer": ""
  },
  {
    "en": "Chik Bik Ji Jin - Saam Gwok Ji (Asia) (Unl)",
    "zh": "三国志-赤壁之战",
    "category": "动作冒险",
    "popularity": 87,
    "classic": 89,
    "recommendation": 90,
    "fun_score": 88.6,
    "rank": 70,
    "complexity": "复杂",
    "players": "多人",
    "saveable": "不支持存档",
    "data_src": "估算数据",
    "cc": "c2",
    "year": "",
    "manufacturer": ""
  },
  {
    "en": "Fatal Fury (Europe)",
    "zh": "饿狼传说（欧）",
    "category": "格斗游戏",
    "popularity": 87,
    "classic": 91,
    "recommendation": 87,
    "fun_score": 88.4,
    "rank": 71,
    "complexity": "复杂",
    "players": "双人对战",
    "saveable": "不支持存档",
    "data_src": "估算数据",
    "cc": "c0",
    "year": "",
    "manufacturer": ""
  },
  {
    "en": "Sangokushi III (Hong Kong)",
    "zh": "三国志3（香港）",
    "category": "动作冒险",
    "popularity": 86,
    "classic": 93,
    "recommendation": 86,
    "fun_score": 88.4,
    "rank": 72,
    "complexity": "复杂",
    "players": "多人",
    "saveable": "不支持存档",
    "data_src": "估算数据",
    "cc": "c2",
    "year": "",
    "manufacturer": ""
  },
  {
    "en": "Super Sangokushi (Japan)",
    "zh": "超级三国志",
    "category": "动作冒险",
    "popularity": 86,
    "classic": 93,
    "recommendation": 86,
    "fun_score": 88.4,
    "rank": 73,
    "complexity": "复杂",
    "players": "多人",
    "saveable": "支持存档",
    "data_src": "估算数据",
    "cc": "c2",
    "year": "",
    "manufacturer": ""
  },
  {
    "en": "Jackal(World-8-wayJoystick)",
    "zh": "赤色要塞",
    "category": "射击游戏",
    "popularity": 88,
    "classic": 90,
    "recommendation": 86,
    "fun_score": 88.1,
    "rank": 74,
    "players": "双人合作",
    "complexity": "简单",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c1",
    "year": "1986",
    "manufacturer": "Konami"
  },
  {
    "en": "SangokushiII:SanShengJian(Chinesebootlegset1-",
    "zh": "三国志三圣剑",
    "category": "动作冒险",
    "popularity": 86,
    "classic": 90,
    "recommendation": 88,
    "fun_score": 88.0,
    "rank": 75,
    "complexity": "复杂",
    "players": "多人",
    "saveable": "不支持存档",
    "data_src": "估算数据",
    "cc": "c2",
    "year": "",
    "manufacturer": ""
  },
  {
    "en": "SaulabiSpirits/JinSaulabiTuHon(Koreanreleaseo",
    "zh": "真侍魂(侍魂II韩版)",
    "category": "格斗游戏",
    "popularity": 85,
    "classic": 89,
    "recommendation": 90,
    "fun_score": 87.9,
    "rank": 76,
    "complexity": "复杂",
    "players": "双人对战",
    "saveable": "不支持存档",
    "data_src": "估算数据",
    "cc": "c0",
    "year": "",
    "manufacturer": ""
  },
  {
    "en": "SamuraiShodownIV-Amakusa'sRevenge/SamuraiSpiri",
    "zh": "侍魂IV-天草降临",
    "category": "格斗游戏",
    "popularity": 86,
    "classic": 91,
    "recommendation": 86,
    "fun_score": 87.8,
    "rank": 77,
    "players": "双人合作",
    "complexity": "复杂",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c0",
    "year": "",
    "manufacturer": ""
  },
  {
    "en": "San Guo Zhi - Qun Xiong Zheng Ba (Asia) (Unl)",
    "zh": "三国志-群雄争霸",
    "category": "动作冒险",
    "popularity": 86,
    "classic": 91,
    "recommendation": 86,
    "fun_score": 87.8,
    "rank": 78,
    "complexity": "复杂",
    "players": "多人",
    "saveable": "不支持存档",
    "data_src": "估算数据",
    "cc": "c2",
    "year": "",
    "manufacturer": ""
  },
  {
    "en": "Sangokushi Eiketsuden (Japan)",
    "zh": "三国志英杰传",
    "category": "动作冒险",
    "popularity": 86,
    "classic": 89,
    "recommendation": 88,
    "fun_score": 87.7,
    "rank": 79,
    "complexity": "复杂",
    "players": "多人",
    "saveable": "支持存档",
    "data_src": "估算数据",
    "cc": "c2",
    "year": "",
    "manufacturer": ""
  },
  {
    "en": "FatalFury2/GarouDensetsu2-arata-narutatakai(",
    "zh": "饿狼传说2-新的战斗",
    "category": "格斗游戏",
    "popularity": 87,
    "classic": 90,
    "recommendation": 85,
    "fun_score": 87.4,
    "rank": 80,
    "players": "双人对战",
    "complexity": "复杂",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c0",
    "year": "1992",
    "manufacturer": "SNK"
  },
  {
    "en": "Hungry Wolf Legend",
    "zh": "饿狼传说",
    "category": "格斗游戏",
    "popularity": 84,
    "classic": 90,
    "recommendation": 88,
    "fun_score": 87.3,
    "rank": 81,
    "complexity": "复杂",
    "players": "双人对战",
    "saveable": "不支持存档",
    "data_src": "估算数据",
    "cc": "c0",
    "year": "",
    "manufacturer": ""
  },
  {
    "en": "Garou Densetsu 2 - Aratanaru Tatakai (Japan)",
    "zh": "饿狼传说2（日）",
    "category": "格斗游戏",
    "popularity": 85,
    "classic": 91,
    "recommendation": 85,
    "fun_score": 87.1,
    "rank": 82,
    "players": "双人合作",
    "complexity": "复杂",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c0",
    "year": "",
    "manufacturer": ""
  },
  {
    "en": "Hot Fighting Soul",
    "zh": "热斗侍魂",
    "category": "格斗游戏",
    "popularity": 86,
    "classic": 90,
    "recommendation": 84,
    "fun_score": 86.8,
    "rank": 83,
    "players": "双人合作",
    "complexity": "复杂",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c0",
    "year": "",
    "manufacturer": ""
  },
  {
    "en": "Knights of the Round (USA)",
    "zh": "圆桌骑士（美）",
    "category": "格斗游戏",
    "popularity": 85,
    "classic": 87,
    "recommendation": 88,
    "fun_score": 86.6,
    "rank": 84,
    "players": "多人",
    "complexity": "中等",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c0",
    "year": "1991",
    "manufacturer": "Capcom"
  },
  {
    "en": "FatalFurySpecial/GarouDensetsuSpecial(set1)(NG",
    "zh": "饿狼传说特别版",
    "category": "格斗游戏",
    "popularity": 82,
    "classic": 88,
    "recommendation": 90,
    "fun_score": 86.5,
    "rank": 85,
    "players": "双人对战",
    "complexity": "复杂",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c0",
    "year": "1993",
    "manufacturer": "SNK"
  },
  {
    "en": "Samurai Spirits (Japan)",
    "zh": "侍魂（日）",
    "category": "格斗游戏",
    "popularity": 86,
    "classic": 87,
    "recommendation": 85,
    "fun_score": 86.0,
    "rank": 86,
    "players": "双人对战",
    "complexity": "复杂",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c0",
    "year": "1993",
    "manufacturer": "SNK"
  },
  {
    "en": "KnightsoftheRound(911127etc)",
    "zh": "圆桌骑士",
    "category": "格斗游戏",
    "popularity": 85,
    "classic": 87,
    "recommendation": 85,
    "fun_score": 85.7,
    "rank": 87,
    "players": "多人",
    "complexity": "中等",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c0",
    "year": "1991",
    "manufacturer": "Capcom"
  },
  {
    "en": "SamuraiShodownVSpecial/SamuraiSpiritsZeroSpeci",
    "zh": "侍魂V特别版/侍魂零特别版",
    "category": "格斗游戏",
    "popularity": 81,
    "classic": 91,
    "recommendation": 85,
    "fun_score": 85.7,
    "rank": 88,
    "players": "双人合作",
    "complexity": "复杂",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c0",
    "year": "",
    "manufacturer": ""
  },
  {
    "en": "Garou Densetsu - Shukumei no Tatakai (Japan)",
    "zh": "饿狼传说（日）",
    "category": "格斗游戏",
    "popularity": 83,
    "classic": 89,
    "recommendation": 85,
    "fun_score": 85.7,
    "rank": 89,
    "complexity": "复杂",
    "players": "双人对战",
    "saveable": "不支持存档",
    "data_src": "估算数据",
    "cc": "c0",
    "year": "",
    "manufacturer": ""
  },
  {
    "en": "SamuraiShodownII/ShinSamuraiSpirits-Haohmaruj",
    "zh": "侍魂II/真侍魂-霸王丸地狱变",
    "category": "格斗游戏",
    "popularity": 83,
    "classic": 88,
    "recommendation": 86,
    "fun_score": 85.6,
    "rank": 90,
    "players": "双人对战",
    "complexity": "复杂",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c0",
    "year": "1993",
    "manufacturer": "SNK"
  },
  {
    "en": "Fatal Fury 2 (USA)",
    "zh": "饿狼传说2（美）",
    "category": "格斗游戏",
    "popularity": 82,
    "classic": 88,
    "recommendation": 87,
    "fun_score": 85.6,
    "rank": 91,
    "complexity": "复杂",
    "players": "双人对战",
    "saveable": "不支持存档",
    "data_src": "估算数据",
    "cc": "c0",
    "year": "",
    "manufacturer": ""
  },
  {
    "en": "SamuraiShodown/SamuraiSpirits(NGM-045)",
    "zh": "侍魂I-十二剑手",
    "category": "格斗游戏",
    "popularity": 83,
    "classic": 88,
    "recommendation": 85,
    "fun_score": 85.3,
    "rank": 92,
    "players": "双人对战",
    "complexity": "复杂",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c0",
    "year": "2003",
    "manufacturer": "Yuki Enterprise / SNK Playmore"
  },
  {
    "en": "SamuraiShodownIII/SamuraiSpirits-ZankurouMusou",
    "zh": "侍魂III-斩红郎无双剑",
    "category": "格斗游戏",
    "popularity": 81,
    "classic": 89,
    "recommendation": 85,
    "fun_score": 85.0,
    "rank": 93,
    "players": "双人对战",
    "complexity": "复杂",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c0",
    "year": "1993",
    "manufacturer": "SNK"
  },
  {
    "en": "Bubble Bobble (USA)",
    "zh": "泡泡龙（美）",
    "category": "平台跳跃",
    "popularity": 82,
    "classic": 82,
    "recommendation": 85,
    "fun_score": 82.9,
    "rank": 94,
    "players": "双人合作",
    "complexity": "简单",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c3",
    "year": "1986",
    "manufacturer": "Taito Corporation"
  },
  {
    "en": "Bubble Bobble Part 2 (USA)",
    "zh": "泡泡龙2（美）",
    "category": "平台跳跃",
    "popularity": 80,
    "classic": 86,
    "recommendation": 81,
    "fun_score": 82.4,
    "rank": 95,
    "players": "双人合作",
    "complexity": "简单",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c3",
    "year": "1986",
    "manufacturer": "Taito Corporation"
  },
  {
    "en": "Mighty Bomb Jack (USA)",
    "zh": "炸弹人杰克（美）",
    "category": "其他游戏",
    "popularity": 80,
    "classic": 84,
    "recommendation": 83,
    "fun_score": 82.3,
    "rank": 96,
    "complexity": "简单",
    "players": "多人",
    "saveable": "支持存档",
    "data_src": "估算数据",
    "cc": "c9",
    "year": "",
    "manufacturer": ""
  },
  {
    "en": "Super Bust-A-Move(US)",
    "zh": "超级泡泡龙",
    "category": "益智游戏",
    "popularity": 79,
    "classic": 86,
    "recommendation": 81,
    "fun_score": 82.0,
    "rank": 97,
    "players": "多人",
    "complexity": "简单",
    "saveable": "支持存档",
    "data_src": "真实数据",
    "cc": "c5",
    "year": "1994",
    "manufacturer": "Taito Corporation"
  },
  {
    "en": "Bomber legend",
    "zh": "炸弹人传说",
    "category": "其他游戏",
    "popularity": 78,
    "classic": 85,
    "recommendation": 83,
    "fun_score": 81.9,
    "rank": 98,
    "complexity": "简单",
    "players": "多人",
    "saveable": "不支持存档",
    "data_src": "估算数据",
    "cc": "c9",
    "year": "",
    "manufacturer": ""
  },
  {
    "en": "NeoBomberman",
    "zh": "炸弹人机皇版",
    "category": "其他游戏",
    "popularity": 80,
    "classic": 84,
    "recommendation": 81,
    "fun_score": 81.7,
    "rank": 99,
    "complexity": "简单",
    "players": "多人",
    "saveable": "支持存档",
    "data_src": "估算数据",
    "cc": "c9",
    "year": "",
    "manufacturer": ""
  },
  {
    "en": "BubbleBobbleII(Ver0.0J1993/12/13-prototype)",
    "zh": "泡泡龙II",
    "category": "平台跳跃",
    "popularity": 80,
    "classic": 83,
    "recommendation": 82,
    "fun_score": 81.6,
    "rank": 100,
    "players": "双人合作",
    "complexity": "简单",
    "saveable": "不支持存档",
    "data_src": "真实数据",
    "cc": "c3",
    "year": "",
    "manufacturer": ""
  }
];
